#!/bin/env python

# ---- python debug
# https://switowski.com/blog/ipython-debugging


```# Put breakpoint in code
import pdb;pdb.set_trace()
# Use h on the pdb command line to se see available commands```

More advanced (autocomplete, colors, contex) `ipdb` (pip installable)

```# Put breakpoint in code
import ipdb;ipdb.set_trace(context=30)
# Use h on the pdb command line to se see available commands```

# Using embed - run ipython at desired cmd line
from IPython import embed; embed()



# --------------
# ---- Conda
# --------------

# conda create
conda create --name ENV_NAME python=3.7.9
# conda remove
conda env remove -n ENV_NAME
