#!/bin/env python

# ---- python debug

```# Put breakpoint in code
import pdb;pdb.set_trace()
# Use h on the pdb command line to se see available commands```

More advanced (autocomplete, colors, contex) `ipdb` (pip installable)

```# Put breakpoint in code
import ipdb;ipdb.set_trace(context=30)
# Use h on the pdb command line to se see available commands```
